options:
 
  auth:
    type: string
    description: |
        Authentication credentials for accessing the camlistore
        website. Example: "userpass:alice:secret"

#  httpsCert:
#    type: string
#    descrption: |
#        TLS public PEM certificate, with any necessary intermediates
#        concatenated.
#
#  httpsKey:
#    type: string
#    description: TLS private key in PEM format.
#
